### ISSUE TITLE
Bot won't open chests with slabs on top of them

### ISSUE THREAD

**Issue by ascentfevers** [michaelzangl/minebot#268] opened 2019-01-10 18:37 UTC
I tried to store some items with /minebot store.
There is a chest with a slab on top of it. I can open it, so the bot should be able to open it too.
But it thinks that the container is blocked and it can't be opened.
I already checked that there is an item frame with the desired item on the chest, and that I have the item in my inventory.

**Comment by xpr0legendx** [comment] 2019-02-14 19:51
Am unable to reproduce this. Tested with both trapped chests and normal ones, with slabs at the bottem and top. Either you do not have the right item in the item frame you wish to store or there are blocks in the way that obstruct the path to the chest. In some scenarios it will think it is obstructed when it's not, there are a few criteria that must be met in order for the bug to occur. In most cases, this is simply fixed by having atleast 2 blocks of free space at the side of the chests of which you are opening it from.

**Comment by michaelzangl** [comment] 2020-05-17 19:35
Fixed now - bot will use the same test as minecraft does if a chest may be opened.

**Closed as completed by michaelzangl** 2020-05-17 19:35 UTC
